

-- STOCK_TRADES --
SELECT DISTINCT SYMBOL from STOCK_TRADES;

SELECT SYMBOL,TRADE_DATE,CLOSE_PRICE from STOCK_TRADES WHERE ("SYMBOL"='AMZN') ORDER BY TRADE_DATE;
SELECT SYMBOL,TRADE_DATE,CLOSE_PRICE from STOCK_TRADES WHERE ("SYMBOL"='RACE') ORDER BY TRADE_DATE;

SELECT DISTINCT SYMBOL,TRADE_DATE,CLOSE_PRICE from STOCK_TRADES WHERE ("SYMBOL"='CARZ' AND TRADE_DATE >= '2016-09-01' AND TRADE_DATE <= '2017-08-15') ORDER BY TRADE_DATE;
SELECT DISTINCT SYMBOL,TRADE_DATE,CLOSE_PRICE from STOCK_TRADES WHERE ("SYMBOL"='RACE' AND TRADE_DATE >= '2016-09-01' AND TRADE_DATE <= '2017-08-15') ORDER BY TRADE_DATE;
SELECT DISTINCT SYMBOL,TRADE_DATE,CLOSE_PRICE from STOCK_TRADES WHERE ("SYMBOL"='MGM' AND TRADE_DATE >= '2016-09-01' AND TRADE_DATE <= '2017-08-15') ORDER BY TRADE_DATE;
SELECT DISTINCT SYMBOL,TRADE_DATE,CLOSE_PRICE from STOCK_TRADES WHERE ("SYMBOL"='STAY' AND TRADE_DATE >= '2016-09-01' AND TRADE_DATE <= '2017-08-15') ORDER BY TRADE_DATE;


-- STOCK_ANALYSIS --
SELECT DISTINCT SYMBOL1, SYMBOL2 from STOCK_ANALYSIS;
SELECT * FROM STOCK_ANALYSIS WHERE ("SYMBOL1"='RACE' AND "SYMBOL2"='HMC');
SELECT * FROM STOCK_ANALYSIS WHERE ("SYMBOL1"='HMC' AND "SYMBOL2"='RACE');

-- CURRENCY_RATES --
SELECT DISTINCT CURRENCY FROM CURRENCY_RATES;
SELECT * FROM CURRENCY_RATES WHERE ("CURRENCY"='DEXUSEU');

-- CURRENCY_ANALYSIS --
SELECT DISTINCT SYMBOL, CURRENCY from CURRENCY_ANALYSIS;
SELECT * FROM CURRENCY_ANALYSIS WHERE ("SYMBOL"='HMC' AND "CURRENCY"='DEXJPUS') ORDER BY TRADE_DATE DESC;


-- CURRENCY_ANALYSIS --
SELECT * FROM BLUADMIN.MACRO_ECONOMIC_DATA;


-- CURRENCY_ANALYSIS --
SELECT * FROM BLUADMIN.STOCKNEWS FETCH FIRST 20 ROWS ONLY;
SELECT * FROM BLUADMIN.STOCKNEWS WHERE (NEWS_TITLE LIKE 'The US dollar will rebound%');
SELECT * FROM BLUADMIN.STOCKNEWS WHERE (NEWS_TITLE LIKE 'Donald Trump and the Stock Market%');
SELECT * FROM BLUADMIN.STOCKNEWS WHERE (NEWS_DATE <= '2017-07-19 09:00:00.000000000') ORDER BY NEWS_DATE DESC FETCH FIRST 8 ROWS ONLY;

SELECT MIN(NEWS_DATE) AS NEWS_DATE, MIN(NEWS_SRC) AS NEWS_SRC, MIN(NEWS_URL) AS NEWS_URL, NEWS_TITLE, MIN(NEWS_TEXT) AS NEWS_TEXT
FROM BLUADMIN.STOCKNEWS
WHERE (NEWS_DATE <= '2016-11-12 05:40:00.000000000' AND NEWS_DATE >= '2016-11-01 00:00:00.000000000')
GROUP BY NEWS_TITLE
ORDER BY NEWS_DATE DESC, NEWS_TITLE DESC
FETCH FIRST 8 ROWS ONLY;


-- BROKERAGE_CUST --
SELECT * FROM BROKERAGE_CUST WHERE ("CustID" < 1000030) ORDER BY "CustID" ASC;
SELECT "CustID", "AccountBalance" FROM BROKERAGE_CUST WHERE "CustID"=1000012;


-- PREDICTIONS --
SELECT * FROM PREDICTIONS;
SELECT * FROM PREDICTIONS_;

